version: 0.2
phases:
  pre_build:
    commands:
      - echo "Pré build phase - Exemplo baixar dependências se fosse necessario"
  build:
    commands:
      - echo "Testing
      - mvn clean test
      - echo "Building"
      - mvn clean compile package
  post_build:
    commands:
      - echo "Movendo os arquivos quie seráo feitos upload"
      - mv target/*.war ./ROOT.war
artifacts:
  files:
    - ROOT.war